language: php

php:
  - 7.0
  - 7.1

install:
  # install composer dependencies
  - composer install

script:
  # run tests
  - vendor/bin/phpunit --coverage-clover coverage.xml
  # check coding standard (defined in composer.json "scripts" section)
  # if this fails, run "composer fs" to fix all fixable issues
  - composer cs
  # check with phpstan (defined in composer.json "scripts" section)
  - composer ps

after_script:
  # upload coverage.xml file to Coveralls to analyze it
  - |
    wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
    php coveralls.phar --verbose
