services:
    _defaults:
        autowire: true

    # Use PSR-4 based
    AppBundle\:
        resource: ../../src/AppBundle

    AppBundle\Service\TwitterAPIService:
        arguments: [ "%twitter.access%", "%twitter.queries%" ]
